export const countriesMock = [
  "Nova Iorque, Estados Unidos",
  "Toronto, Canadá",
  "Cidade do México, México",
  "Rio de Janeiro, Brasil",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Bogotá, Colômbia",
  "Lima, Peru",
  "Madri, Espanha",
  "Paris, França",
  "Berlim, Alemanha",
  "Londres, Reino Unido",
  "Roma, Itália",
  "Amsterdã, Países Baixos",
  "Zurique, Suíça",
  "Sydney, Austrália",
  "Tóquio, Japão",
  "Pequim, China",
  "Nova Délhi, Índia",
  "Seul, Coreia do Sul",
  "Singapura, Singapura",
];