import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { 
  ReactQueryProvider, 
  ToastProvider, 
  RouteProtectionProvider 
} from "@/src/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plann.er",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ToastProvider>
            <RouteProtectionProvider>
              {children}
            </RouteProtectionProvider>
          </ToastProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
