import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ReactQueryProvider,
  ToastProvider,
  RouteProtectionProvider,
  AccessibilityProvider,
} from "@/src/providers";
import { SkipLinks } from "@/src/components/primitives/SkipLinks/SkipLinks";
import { KeyboardShortcutsHelp } from "@/src/components/compounds/KeyboardShortcutsHelp/KeyboardShortcutsHelp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plann.er",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <SkipLinks />
        <ReactQueryProvider>
          <ToastProvider>
            <AccessibilityProvider>
              <RouteProtectionProvider>
                {children}
                <KeyboardShortcutsHelp />
              </RouteProtectionProvider>
            </AccessibilityProvider>
          </ToastProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
