import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ReactQueryProvider,
  ToastProvider,
  RouteProtectionProvider,
  AccessibilityProvider,
  LocaleProvider,
} from "@/src/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plann.er",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <LocaleProvider>
          <ReactQueryProvider>
            <ToastProvider>
              <AccessibilityProvider>
                <RouteProtectionProvider>{children}</RouteProtectionProvider>
              </AccessibilityProvider>
            </ToastProvider>
          </ReactQueryProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
