import { tv } from "tailwind-variants";

export const accessibilityPanelVariants = tv({
  slots: {
    sPanel: ["relative", "inline-block"],
    sTrigger: [
      "flex",
      "items-center",
      "justify-center",
      "w-10",
      "h-10",
      "rounded-lg",
      "bg-zinc-800",
      "hover:bg-zinc-700",
      "text-zinc-300",
      "hover:text-white",
      "transition-colors",
      "duration-200",
      "focus:outline-none",
    ],
    sDropdown: [
      "absolute",
      "right-0",
      "top-full",
      "mt-2",
      "w-80",
      "bg-white",
      "dark:bg-zinc-800",
      "border",
      "border-zinc-200",
      "dark:border-zinc-700",
      "rounded-lg",
      "shadow-lg",
      "z-50",
      "py-4",
    ],
    sHeader: [
      "px-4",
      "pb-3",
      "border-b",
      "border-zinc-200",
      "dark:border-zinc-700",
    ],
    sTitle: ["text-sm", "font-semibold", "text-zinc-900", "dark:text-zinc-100"],
    sSubtitle: ["text-xs", "text-zinc-500", "dark:text-zinc-400", "mt-1"],
    sSection: ["px-4", "py-3"],
    sSectionTitle: [
      "text-sm",
      "font-medium",
      "text-zinc-900",
      "dark:text-zinc-100",
      "mb-3",
    ],
    sFontControls: ["flex", "items-center", "gap-2"],
    sFontButton: [
      "flex",
      "items-center",
      "justify-center",
      "w-8",
      "h-8",
      "rounded",
      "border",
      "border-zinc-300",
      "dark:border-zinc-600",
      "bg-white",
      "dark:bg-zinc-700",
      "text-zinc-700",
      "dark:text-zinc-200",
      "hover:bg-zinc-50",
      "dark:hover:bg-zinc-600",
      "transition-colors",
      "duration-150",
      "focus:outline-none",
      "focus:ring-2",
      "focus:ring-lime-500",
    ],
    sFontButtonActive: [
      "bg-lime-100",
      "dark:bg-lime-900",
      "border-lime-500",
      "text-lime-700",
      "dark:text-lime-200",
    ],
    sToggleContainer: ["flex", "items-center", "justify-between"],
    sToggleLabel: ["text-sm", "text-zinc-700", "dark:text-zinc-300"],
    sToggle: [
      "relative",
      "inline-flex",
      "min-h-6",
      "min-w-11",
      "items-center",
      "rounded-full",
      "bg-zinc-200",
      "dark:bg-zinc-700",
      "transition-colors",
      "duration-200",
      "focus:outline-none",
    ],
    sToggleActive: ["bg-lime-300"],
    sToggleThumb: [
      "inline-block",
      "h-4",
      "w-4",
      "transform",
      "rounded-full",
      "bg-white",
      "transition-transform",
      "duration-200",
    ],
    sToggleThumbActive: ["translate-x-6", "bg-lime-300"],
  },
  variants: {
    fontSize: {
      small: {},
      medium: {},
      large: {},
    },
    enhancedFocus: {
      true: {},
      false: {},
    },
  },
});

export const {
  sPanel,
  sTrigger,
  sDropdown,
  sHeader,
  sTitle,
  sSubtitle,
  sSection,
  sSectionTitle,
  sFontControls,
  sFontButton,
  sFontButtonActive,
  sToggleContainer,
  sToggleLabel,
  sToggle,
  sToggleActive,
  sToggleThumb,
  sToggleThumbActive,
} = accessibilityPanelVariants();
